# Generated by Django 4.2.16 on 2024-11-21 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepositProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kor_co_nm', models.CharField(max_length=100)),
                ('fin_prdt_nm', models.CharField(max_length=200)),
                ('intr_rate_type', models.CharField(max_length=50)),
                ('save_trm', models.CharField(max_length=50)),
                ('intr_rate', models.FloatField()),
                ('intr_rate2', models.FloatField()),
                ('join_way', models.CharField(max_length=200)),
                ('spcl_cnd', models.CharField(max_length=200)),
                ('join_deny', models.CharField(max_length=200)),
                ('join_member', models.CharField(max_length=200)),
                ('etc_note', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SavingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kor_co_nm', models.CharField(max_length=100)),
                ('fin_prdt_nm', models.CharField(max_length=200)),
                ('intr_rate_type', models.CharField(max_length=50)),
                ('save_trm', models.CharField(max_length=50)),
                ('intr_rate', models.FloatField()),
                ('intr_rate2', models.FloatField()),
                ('join_way', models.CharField(max_length=200)),
                ('spcl_cnd', models.CharField(max_length=200)),
                ('join_deny', models.CharField(max_length=200)),
                ('join_member', models.CharField(max_length=200)),
                ('etc_note', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
