# Generated by Django 4.2.16 on 2024-11-18 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_unit', models.CharField(max_length=10)),
                ('exchange_rate', models.FloatField()),
                ('date', models.DateField()),
            ],
        ),
    ]
